package ClientServer;

import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Client extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientChatWindow = new javax.swing.JTextArea();
        messageBox = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setPreferredSize(new java.awt.Dimension(627, 531));

        clientChatWindow.setEditable(false);
        clientChatWindow.setColumns(20);
        clientChatWindow.setRows(5);
        jScrollPane1.setViewportView(clientChatWindow);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageBox)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sendMessage(messageBox.getText());
                if (messageBox.getText().equalsIgnoreCase("Client: exit")) {
                    System.exit(0);
                }
                messageBox.setText("");
            }
        });
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clientChatWindow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageBox;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
    private Socket client;
    private ObjectOutputStream serverOutput;
    private ObjectInputStream serverInput;
    private final String serverIP = "127.0.0.1"; //Loopback address

    public void startClient() {
        try {
            connectToServer();
            chat();
        } catch (EOFException eofE) {
            printToGUI("\nClient terminated the connection");
        } catch (IOException ioE) {
                printToGUI("\nServer has terminated the connection");
        } finally {
            closeConnection();
        }
    }

    public void connectToServer() throws IOException {
        printToGUI("Attempting to connect to the server");
        client = new Socket(serverIP, Server.PORT);
        printToGUI("Now connected to " + client.getInetAddress().getHostName());

        serverOutput = new ObjectOutputStream(client.getOutputStream());
        serverOutput.flush();
        serverInput = new ObjectInputStream(client.getInputStream());
    }

    public void chat() throws IOException {
        String message = "";
        while (!message.equalsIgnoreCase("Server: exit")) {
            try {
                message = (String) serverInput.readObject();
                printToGUI(message);
            } catch (ClassNotFoundException ex) {
                System.out.println("Object not found");
            }

        }
    }

    public void closeConnection() {
        try {
            serverInput.close();
            serverOutput.close();
            client.close();
        } catch (IOException ex) {
            System.out.println("Error closing connection");
        }
    }
    
    private void sendMessage(String message) {
        try {
            message = "Client: " + message;
            serverOutput.writeObject(message);
            serverOutput.flush();
            printToGUI(message);
        } catch (IOException ex) {
            System.out.println("Message could not be sent");
        }
    }
    
    private void printToGUI(String message) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                clientChatWindow.append("\n" + message);
            }
        });
    }

}
